---
- name: create kubeadm-configure YAML file
  template:
    src: kubeadm-config.yaml.j2
    dest: "{{ lookup('env','HOME') }}/kubeadm-config.yaml"

- name: execute kubeadm init
  shell: kubeadm init --config "{{ lookup('env','HOME') }}/kubeadm-config.yaml" --upload-certs

- name: create $HOME/.kube directory
  file:
    path: "{{ lookup('env','HOME') }}/.kube/"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"

- name: copy admin.conf to $HOME/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ lookup('env','HOME') }}/.kube/config"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0600'
    remote_src: true
